networks:
  laravel_network:
services:
  server:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - 8080:80
    volumes:
      - ./www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
    container_name: laravel_server
    networks:
      - laravel_network

  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./www:/var/www/html:delegated
    container_name: laravel_php
#    environment:
#      XDEBUG_MODE: develop, debug
#      XDEBUG_CONFIG:
#        client_host=host.docker.internal
#        start_with_request=yes
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - laravel_network
    
  mysql:
    image: mysql:8.0.1
    restart: unless-stopped
    tty: true
    container_name: laravel_mysql
    env_file:
      - mysql/.env
    ports:
      - 3310:3306
    networks:
      - laravel_network
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    container_name: laravel_phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root.pa55
    networks:
      - laravel_network

  composer:
    build:
      context: .
      dockerfile: dockerfiles/composer.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./www:/var/www/html
    depends_on:
      - php
    entrypoint: [ 'composer', '--ignore-platform-reqs' ]
    networks:
      - laravel_network

  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./www:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      - laravel_network

  code-server:
    image: linuxserver/code-server
    container_name: code-server
    environment:
      - PASSWORD=GIANCARLO
      - TZ='America/Lima'
      - DEFAULT_WORKSPACE=/home
    volumes:
      - ./vscode:/config
      - ./www:/home
    ports:
      - 8443:8443
    restart: unless-stopped
    networks:
      - laravel_network